#!/bin/bash

PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_RX="$2"
PPP_TX="$3"
PPP_DATE=$(date)
export PPP_IFACE

#rx=$(cat /sys/class/net/$PPP_IFACE/statistics/rx_bytes)
#tx=$(cat /sys/class/net/$PPP_IFACE/statistics/tx_bytes)

let PPP_RX=PPP_RX+PPP_TX

curl -X POST http://147.178.202.19/admin/stopuserlog -d "interface=$PPP_IFACE" -d "traffic=$PPP_RX"
echo "$PPP_IFACE $PPP_RX $PPP_DATE ip-pre-down" >> /var/log/ippredown.log
