#!/bin/bash

PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM

rx=$(cat /sys/class/net/$PPP_IFACE/statistics/rx_bytes)
tx=$(cat /sys/class/net/$PPP_IFACE/statistics/tx_bytes)

let rx=rx+tx

curl -X POST localhost:5000/admin/stopuserlog -d "interface=$PPP_IFACE" -d "traffic=$rx"
